version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jatindesai/employee:0.0.1
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.3"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "8181:8080"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet      
  mongodb:
    image: mongo
    ports:
      - "32600:27017"
    volumes:
      - ./data:/data/db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
